Repository stlatica/stlatica, pull requests merged in 2023-08, with the labels that each got.

#43 Add golangci lint settings
  packages/backend/.golangci.yaml
  packages/backend/.vscode/settings.json
  packages/backend/Makefile
  packages/backend/app/cmd/api/main.go
  packages/backend/go.mod
  packages/backend/go.sum
  packages/backend/tools/tools.go
Labels: backend

#45 Docker構築
  packages/docker-compose.yaml
  packages/frontend/Dockerfile
Labels: frontend, environment

#65 #61 power up Readme
  README.md
Labels: documentation

#74 Add pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: environment

#76 ladleのCDの設定をしました。
  .github/workflows/actions.yml
  packages/frontend/.ladle/config.mjs
Labels: infra

#80 Change issue and pr template placement
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: environment

#78 Add sqlboiler settings
  packages/backend/Makefile
  packages/backend/app/cmd/internalapi/main.go
  packages/backend/app/controllers/internalapi/v1/handler.go
  packages/backend/app/domains/entities/sample_users.go
  packages/backend/app/domains/types/unix_time.go
  packages/backend/app/repositories/entities/boil_queries.go
  packages/backend/app/repositories/entities/boil_table_names.go
  packages/backend/app/repositories/entities/boil_types.go
  packages/backend/app/repositories/entities/boil_view_names.go
  packages/backend/app/repositories/entities/sample_users.go
  packages/backend/db/sqlboiler.toml
  packages/backend/db/sqlboiler/generate_codes.sh
  packages/backend/db/sqlboiler/sqlboiler.toml
  packages/backend/db/sqlboiler/templates/entities.go.tpl
  packages/backend/go.mod
  packages/backend/go.sum
  packages/backend/tools/tools.go
Labels: backend

#84 フロントのTODOコメント削除
  packages/frontend/.eslintrc.json
  packages/frontend/src/utilities/utilities.ts
Labels: frontend

#83 D2 cd setting
  .github/workflows/build_d2.sh
  .github/workflows/text2Diagram.yml
  docs/d2_sample/README.md
  docs/d2_sample/test.d2
  docs/d2_sample/test.svg
Labels: infra
