Repository stlatica/stlatica, pull requests merged in 2024-03, with the labels that each got.

#292 Login scene/#237
  packages/frontend/playwright/snapshots/snapshot.test.ts-snapshots/components--button--loginbutton--login-button-visual-snapshot-linux.png
  packages/frontend/src/app/login/page.tsx
  packages/frontend/src/app/page.tsx
  packages/frontend/src/components/button/LoginButton/LoginButton.stories.tsx
  packages/frontend/src/components/button/LoginButton/LoginButton.tsx
  packages/frontend/src/components/button/LoginButton/index.ts
Labels: frontend

#288 user作成・削除・取得のendpointをopenapiで定義
  packages/shared/openapi/internalapi/openapi.yaml
  packages/shared/openapi/internalapi/paths/users.yaml
  packages/shared/openapi/internalapi/schemas/ErrorResponse.yaml
Labels: backend

#321 query parameterを使用してtimelineを取得するendpointを追加
  packages/shared/openapi/internalapi/openapi.yaml
  packages/shared/openapi/internalapi/parameters/timeline_queries.yaml
  packages/shared/openapi/internalapi/paths/timelines.yaml
Labels: backend

#329 【backend】モックサーバー起動コマンドの追加
  packages/backend/Makefile
Labels: backend

#322 plat作成のusecase layer実装
  packages/backend/app/usecases/plats/usecase.go
Labels: backend

#306 actor tableのスキーマを論理設計に基づき更新
  packages/backend/db/migrations/20231029184844_new_migration.sql
Labels: backend

#379 Fix lint in openapi.yaml
  packages/shared/openapi/internalapi/openapi.yaml
  packages/shared/openapi/internalapi/paths/plats.yaml
  packages/shared/openapi/internalapi/paths/users.yaml
Labels: backend

#377 openapi/redocly周りをdocker化
  packages/shared/openapi/Makefile
  packages/shared/openapi/README.md
  packages/shared/openapi/docker-compose.yaml
  packages/shared/openapi/docker/Dockerfile
  packages/shared/openapi/package.json
  packages/shared/openapi/pnpm-lock.yaml
Labels: environment

#380 APIモックサーバー
  packages/front-mock/.gitignore
  packages/front-mock/.vscode/extensions.json
  packages/front-mock/.vscode/settings.json
  packages/front-mock/Makefile
  packages/front-mock/README.md
  packages/front-mock/biome.json
  packages/front-mock/docker-compose.yaml
  packages/front-mock/nodemon.json
  packages/front-mock/package.json
  packages/front-mock/pnpm-lock.yaml
  packages/front-mock/src/main.ts
  packages/front-mock/src/schema.d.ts
  packages/front-mock/src/utils.ts
Labels: frontend

#319 Nodeinfoのパッケージ実装を追加
  packages/backend/app/pkg/nodeinfo/nodeinfo.go
Labels: backend

#390 external apiのopenapi定義をlintに合わせて修正
  packages/shared/openapi/externalapi/openapi.yaml
Labels: backend

#391 actors tableをusers tableへ変更
  packages/backend/db/migrations/20231029184844_add_users.sql
  packages/backend/db/migrations/20231029184844_new_migration.sql
  packages/backend/db/migrations/20231203180150_add_plats.sql
  packages/backend/db/migrations/20240218205040_add_timelines.sql
  packages/backend/db/migrations/20240218205826_add_timeline_users.sql
Labels: backend

#378 OpenAPIのlint Action追加
  .github/workflows/actions.yml
  packages/shared/openapi/README.md
Labels: infra-ci/cd
